spring.application.name=System_userAndLogin

# Configuracin del puerto de la aplicacin
server.port=8081

# Configuracin de la conexin a PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/PuntoDeVenta
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_Clinica_Veterinaria
#spring.datasource.url=jdbc:postgresql://localhost:5432/clinicaVeterinaria

spring.datasource.username=postgres
spring.datasource.password=1536
# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracin de Hibernate ORM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never
server.error.include-path=never

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER


# --- JWT ---
app.jwt.issuer=clinica-vet-auth
app.jwt.expiration-ms=3600000
app.jwt.secret-base64=/6CAK0DupVzNN6ca8pF55tdxA1yj6e1C95k4N8+hrNLp+s6N4yNw0ic/utzYTNDEeQJfjHc3soHOK9BCb16QIg==